[첨부] 시스템 설계서 v2.0 (System Design)
1. 데이터베이스 스키마 (Supabase SQL Script)
아래 코드를 Supabase SQL Editor에 그대로 붙여넣고 실행하세요.

-- 1. 유저 프로필 (재화 및 상태)
create table profiles (
  id uuid references auth.users not null primary key,
  grade int,
  publisher text, -- 'chunjae', 'ybm'
  level int default 1,
  -- 재화
  energy int default 5,
  gems int default 0,
  -- 상태 및 제한
  is_premium boolean default false,
  vision_usage_today int default 0,
  feedback_usage_today int default 0,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);
-- 2. 상점 아이템 (확장성 고려)
create table shop_items (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null, -- 'outfit', 'decoration'
  cost_gems int not null,
  image_url text
);
-- 3. 유저 인벤토리
create table user_inventory (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) not null,
  item_id bigint references shop_items(id) not null,
  is_equipped boolean default false,
  created_at timestamp default now()
);
-- 4. 학습 로그 (UGC 안전장치 포함)
create table study_logs (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references profiles(id) not null,
  mission_text text,
  user_input text,
  ai_feedback jsonb,
  -- 상태 관리
  status text default 'completed', --