-- ESL Writing App - 초기 스키마
-- 실제 스키마 (docs/02_schema.sql) 기반
-- Supabase SQL Editor에서 실행하거나 Supabase CLI로 마이그레이션

-- UUID 확장 기능 활성화
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. 유저 프로필 (재화 및 상태)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  grade INTEGER,
  publisher TEXT, -- 'chunjae', 'ybm'
  level INTEGER DEFAULT 1,
  -- 재화
  energy INTEGER DEFAULT 5,
  gems INTEGER DEFAULT 0,
  -- 상태 및 제한
  is_premium BOOLEAN DEFAULT false,
  vision_usage_today INTEGER DEFAULT 0,
  feedback_usage_today INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 상점 아이템 (확장성 고려)
CREATE TABLE shop_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL, -- 'outfit', 'decoration'
  cost_gems INTEGER NOT NULL,
  image_url TEXT
);

-- 3. 유저 인벤토리
CREATE TABLE user_inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) NOT NULL,
  item_id BIGINT REFERENCES shop_items(id) NOT NULL,
  is_equipped BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 4. 학습 로그 (UGC 안전장치 포함)
CREATE TABLE study_logs (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) NOT NULL,
  mission_text TEXT,
  user_input TEXT,
  ai_feedback JSONB,
  -- 상태 관리
  status TEXT DEFAULT 'completed', -- 'queued'
  is_public BOOLEAN DEFAULT false, -- 초기엔 false로 고정 (나만의 도서관)
  created_at TIMESTAMP DEFAULT NOW()
);

-- updated_at 자동 업데이트 함수
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- profiles 테이블의 updated_at 트리거
CREATE TRIGGER update_profiles_updated_at 
  BEFORE UPDATE ON profiles
  FOR EACH ROW 
  EXECUTE FUNCTION update_updated_at_column();

-- 성능 인덱싱
CREATE INDEX idx_logs_user_date ON study_logs (user_id, created_at DESC);
CREATE INDEX idx_inventory_user ON user_inventory (user_id);
